# Site settings
title: The Edge of Uncertainty
email: katy@edgeofuncertainty.com
description: > # this means to ignore newlines until "baseurl:"
  Reviews of Adventure Books
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.edgeofuncertainty.com" # the base hostname & protocol for your site
twitter_username: EdgeofU
github_username:  k80bowman

# Build settings
markdown: kramdown
